import type { Metadata } from "next";
import { Geist, Montserrat } from "next/font/google";
import "./globals.css";
import type { ReactNode } from "react";
import { headers } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin", "cyrillic"],
  display: "swap",
});

const montserratAccent = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin", "cyrillic"],
  display: "swap",
  weight: "700",
});

export const metadata: Metadata = {
  title: {
    template: "%s | Next.js course by TeaCoder",
    default: "Next.js course by TeaCoder",
  },
  description: "Generated by create next app",
  keywords: ["nextjs", "web"],
  authors: [
    {
      name: "TeaCoder",
      url: "https://1",
    },
  ],
  creator: "Vadim",
  publisher: "Vadim LLC",
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
    },
  },
  alternates: {
    canonical: "https://teacoder.ru",
  },
  // То что будет отображаться если переслать в телегу например
  openGraph: {
    title: "Next.js course by TeaCoder",
    url: "https://teacoder.ru",
    siteName: "Teacoder",
    locale: "ru_RU",
    type: "website",
    images: [
      {
        url: "https://teacoder/ru/opengraph.png",
        width: 1200,
        height: 630,
        alt: "Open Graph Image",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    creator: "@teacoder",
  },
  icons: {
    icon: "/favicon.ico",
  },
  verification: {
    yandex: "token",
  },
};

interface RootLayoutProps {
  children: ReactNode;
}

export default async function RootLayout({ children }: RootLayoutProps) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${montserratAccent.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
